NOTION_TOKEN = "your notion api token"
DATABASE_ID = "your database id"
NAVER_ID = "your naver id"
NAVER_PW = "your naver pw"
CUSTOMERS = ["your customer1", "your customer2"]
GSPREAD_KEY = "gspread_key.json"
GSPREAD_SHEET_URL = "https://docs.google.com/spreadsheets/"
GSPREAD_SHEET_NAME = "mail-list"
MAIL_COL_NUM = 1